### ISSUE TITLE
create initial WildFly-NoSQL design documentation

### ISSUE THREAD

**Issue by scottmarlow** [jboss/jboss-nosql#11]
Create something on https://developer.jboss.org/wiki (similar to https://developer.jboss.org/wiki/DesignNotesForSupportingManagedExplodedDeployments).

**Comment by emmanuelbernard** [comment]
This wiki is the official way to add documentation to Wildfly? From the look of it, it might simply be lost in this big pool of doc. I wonder how people find it in practice. Also how is that moved to EAP ?

**Comment by scottmarlow** [comment]
Yes, this is the new (old?) official way to add design documentation for WildFly.  I'll share the internal note about this with you.  As far as I know, it is easy to lose documentation in the big pool of doc.  I was able to do a google search to find the [JPA container rewrite doc from a few years back](https://developer.jboss.org/wiki/EJB3JPA20SupportForAS7) (for the AS7 rewrite), but it wasn't easy to find.

**Comment by emmanuelbernard** [comment]
Ah ok, nice.
I thought you mentioned user documentation. but that's more design doc.

**Comment by scottmarlow** [comment]
I started a document to add the [WildFly NoSQL design notes/requirements](https://developer.jboss.org/wiki/DesignNotesForNoSQLIntegrationOnWildFly) here, updates welcome.
